default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[update]
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "93c7b51d860138c34a0613756c0151209b88d56f"  # frozen: v4.17.0
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "e805244dd1bc999f2b4d716f5fa21ee87189b084"  # frozen: 0.12.2
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "a4405bd34b6505ed51226ba2a5b5428625177d6a"  # frozen: v0.0.69
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "39d9ac5938dadb73df0564a45f163e25ff9fa6e2"  # frozen: v0.16.1
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check", args = ["--fix"] },
]
