default_install_hook_types = ["pre-commit", "pre-push", "commit-msg"]
default_stages = ["pre-commit"]

[update]
freeze = true

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-added-large-files" },
  { id = "check-vcs-permalinks" },
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "check-merge-conflict" },
  { id = "check-case-conflict" },
  { id = "mixed-line-ending", args = ["--fix=lf"] },
  { id = "check-symlinks" },
  { id = "detect-private-key" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "https://github.com/commitizen-tools/commitizen"
rev = "93c7b51d860138c34a0613756c0151209b88d56f"  # frozen: v4.17.0
hooks = [
  { id = "commitizen" },
  { id = "commitizen-branch" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "5900cba2cfe6d20f562458d4d308ac55569f92eb"  # frozen: 0.12.0
hooks = [
  { id = "uv-lock" },
]

[[repos]]
repo = "https://github.com/astral-sh/ty-pre-commit"
rev = "3940f891290063e0fde330228f5bff73e18ad2f2"  # frozen: v0.0.64
hooks = [
  { id = "ty" },
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "cb8c523fd4835aba42af70f4cad5568db4df0b6c"  # frozen: v0.16.0
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check", args = ["--fix"] },
]
