[project]
name = "taze"
version = "0.3.0"
description = "🥬 Keep your Python deps fresh"
readme = "README.md"
requires-python = ">=3.14"
license = "MIT"
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
]
dependencies = [
  "packaging>=26.3",
  "pydantic-settings[toml]>=2.15.0",
  "rich>=15.0.0",
  "typer>=0.27.1",
]

[project.scripts]
taze = "taze.main:app"

[dependency-groups]
dev = [
  "commitizen>=4.17.0",
  "prek>=0.4.12",
  "pytest>=9.1.1",
  "ruff>=0.16.1",
  "ty>=0.0.69",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"

[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_files = [
  "pyproject.toml",
  "taze/__init__.py",
]
version_scheme = "pep440"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true

[tool.pytest.ini_options]
cache_dir = ".cache/pytest"
testpaths = ["tests"]

[tool.ruff]
cache-dir = ".cache/ruff"
fix = true
unsafe-fixes = true
line-length = 120

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN", "D", "S101"]

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
known-first-party = ["taze"]
lines-after-imports = 2

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
quote-style = "double"

[tool.taze]
github-actions-pin = true
github-actions-style = "sha"

[tool.tombi.files]
exclude = ["uv.lock"]

[tool.uv.build-backend]
module-name = "taze"
module-root = ""
